import { appStart, timeCommand, parseSelf, parseChannel, parseStatus, parseChannelMessage, channelMessage, nameCommand, decodeEnvelope, encodeEnvelope, PRESENCE_TTL } from './protocol.js';

// The protocol has no command IDs. A timeout makes the connection ambiguous;
// abandon it so a delayed generic OK cannot complete a later command.
export class CommandQueue {
  constructor(write, { timeout = 6000, onFatal = () => {} } = {}) {
    this.write = write; this.timeout = timeout; this.onFatal = onFatal;
    this.items = []; this.current = null; this.closed = false;
  }
  request(frame, codes) {
    if (this.closed) return Promise.reject(new Error('Connection closed; reconnect to continue'));
    return new Promise((resolve, reject) => {
      this.items.push({ frame, codes, resolve, reject }); this.next();
    });
  }
  next() {
    if (this.current || this.closed || !this.items.length) return;
    const item = this.current = this.items.shift();
    item.timer = setTimeout(() => this.fatal(new Error('Command timed out; reconnect before retrying')), this.timeout);
    Promise.resolve().then(() => {
      if (!this.closed && this.current === item) return this.write(item.frame);
    }).catch((error) => this.fatal(error));
  }
  receive(frame) {
    const item = this.current;
    if (!item || (!item.codes.includes(frame[0]) && frame[0] !== 1 && frame[0] !== 15)) return false;
    clearTimeout(item.timer); this.current = null;
    if (frame[0] === 1 || frame[0] === 15) item.reject(new Error(frame[0] === 15 ? 'Command disabled by device' : `Device rejected command (error ${frame[1] ?? '?'})`));
    else item.resolve(frame);
    this.next(); return true;
  }
  close(reason = new Error('Disconnected')) {
    this.closed = true;
    if (this.current) { clearTimeout(this.current.timer); this.current.reject(reason); this.current = null; }
    for (const item of this.items.splice(0)) item.reject(reason);
  }
  fatal(error) { if (!this.closed) { this.close(error); this.onFatal(error); } }
}

export class NetworkState {
  constructor(now = () => performance.now()) { this.now = now; this.roster = new Map(); this.incidents = new Map(); this.messages = []; }
  receive(message) {
    if (message.channel !== 0) return null;
    this.trim();
    const now = this.now();
    const event = decodeEnvelope(message.text);
    if (event?.type !== 'presence') {
      const existing = event ? this.messages.findIndex((entry) => entry.event?.node === event.node && entry.event?.id === event.id) : -1;
      if (existing >= 0) this.messages.splice(existing, 1);
      this.messages.unshift({ ...message, receivedAt: Date.now(), seen: now, event });
      this.messages.length = Math.min(this.messages.length, 150);
    }
    if (!event) return null;
    const previous = this.roster.get(event.node);
    this.roster.delete(event.node);
    this.roster.set(event.node, { node: event.node, name: message.name, seen: now, lat: event.lat ?? previous?.lat, lon: event.lon ?? previous?.lon, type: event.type });
    while (this.roster.size > 128) this.roster.delete(this.roster.keys().next().value);
    if (['sos', 'medical', 'pickup'].includes(event.type)) {
      const key = `${event.node}:${event.id}`;
      const prior = this.incidents.get(key);
      this.incidents.set(key, { ...prior, key, event, name: message.name, outgoing: prior?.outgoing ?? false, status: prior?.status ?? 'Received from network', seen: now });
    } else if (event.type === 'ack') {
      // ACK ids generated by Uni-Fi include the originating node prefix.
      // Also reject an acknowledgement pretending to be from the victim itself.
      for (const incident of this.incidents.values()) {
        if (incident.outgoing && incident.event.id === event.ack && incident.event.node !== event.node) {
          incident.status = `Remote receipt from ${message.name}`;
          incident.ack = { node: event.node, name: message.name };
          incident.seen = now;
        }
      }
    }
    this.trim(); return event;
  }
  sent(event, name) {
    if (['sos', 'medical', 'pickup'].includes(event.type)) {
      const key = `${event.node}:${event.id}`;
      this.incidents.set(key, { key, event, name, outgoing: true, status: 'Queued on device; awaiting remote receipt', seen: this.now() });
    }
    this.trim();
  }
  trim() {
    const now = this.now();
    for (const [node, entry] of this.roster) if (now - entry.seen >= PRESENCE_TTL) this.roster.delete(node);
    for (const [key, entry] of this.incidents) if (now - entry.seen >= PRESENCE_TTL) this.incidents.delete(key);
    this.messages = this.messages.filter((entry) => now - entry.seen < PRESENCE_TTL);
    while (this.incidents.size > 100) this.incidents.delete(this.incidents.keys().next().value);
  }
}

export class DeviceSession {
  constructor(transport, { onChange = () => {}, onLog = () => {}, onDisconnect = () => {} } = {}) {
    this.transport = transport; this.onChange = onChange; this.onLog = onLog; this.onDisconnect = onDisconnect;
    this.network = new NetworkState(); this.ready = false; this.closed = false; this.draining = false; this.drainRequested = false;
    this.queue = new CommandQueue((frame) => transport.write(frame), { onFatal: (error) => { this.onLog(error.message); void this.close(); } });
    transport.onFrame = (frame) => this.receive(frame);
    transport.onDisconnect = () => { void this.close(); };
  }
  async initialize() {
    this.self = parseSelf(await this.queue.request(appStart(), [5]));
    const info = await this.queue.request(Uint8Array.of(22, 3), [13]);
    if (info.length < 80) throw new Error('Malformed device-info frame');
    this.version = new TextDecoder().decode(info.subarray(60, 80)).replace(/\0.*$/, '');
    await this.queue.request(timeCommand(Math.floor(Date.now() / 1000)), [0]);
    this.channel = parseChannel(await this.queue.request(Uint8Array.of(31, 0), [18]));
    if (this.channel.name !== 'Uni-Fi') throw new Error('Slot 0 is not the provisioned Uni-Fi network. Flash the Uni-Fi firmware profile first.');
    if (this.self.frequency !== 910.525 || this.self.bandwidth !== 62.5 || this.self.sf !== 7 || this.self.cr !== 5) throw new Error('Device radio does not match the Uni-Fi 910.525 MHz profile');
    try { this.status = parseStatus(await this.queue.request(Uint8Array.of(0x70), [0x70])); }
    catch (error) {
      if (!/Device rejected command|Command disabled/.test(error.message)) throw error;
      this.status = null; this.onLog('Uni-Fi status command unavailable; provisioning cannot be independently verified.');
    }
    if (this.status && !this.status.provisioned) throw new Error('Device has no Uni-Fi network key provisioned. Flash with a private provisioning key before sending.');
    this.updateOwnIncident();
    this.ready = true; this.onChange();
    this.keepalive = setInterval(() => {
      if (!this.ready || this.draining || this.queue.current || this.queue.items.length) return;
      if (this.status) void this.refreshStatus().catch((error) => this.onLog(error.message));
      else void this.queue.request(Uint8Array.of(5), [9]).catch((error) => this.onLog(error.message));
    }, this.status ? 5000 : 15000);
    await this.drain();
  }
  receive(frame) {
    if (this.closed || !frame.length) return;
    this.onLog(`RX type 0x${frame[0].toString(16).padStart(2, '0')} (${frame.length} bytes)`);
    if (frame[0] === 0x83) {
      this.drainRequested = true;
      if (this.ready) void this.drain().catch((error) => this.onLog(error.message));
      return;
    }
    if (frame[0] === 8 || frame[0] === 17) {
      try { this.network.receive(parseChannelMessage(frame)); this.onChange(); }
      catch (error) { this.onLog(`Ignored message: ${error.message}`); }
    }
    this.queue.receive(frame);
  }
  async drain() {
    if (this.draining || !this.ready || this.closed) return;
    this.draining = true;
    try {
      do {
        this.drainRequested = false;
        let frame;
        do { frame = await this.queue.request(Uint8Array.of(10), [7, 8, 10, 16, 17, 27]); } while (frame[0] !== 10 && !this.closed);
      } while (this.drainRequested && !this.closed);
    } finally { this.draining = false; }
  }
  requireReady() { if (!this.ready || this.closed) throw new Error('Connect and initialize a Uni-Fi device first'); }
  updateOwnIncident() {
    if (!this.status?.ownId || (!this.status.ownWaiting && !this.status.ownAcked)) return;
    const key = `${this.self.node}:${this.status.ownId}`;
    if (!this.network.incidents.has(key)) this.network.sent({ type: 'sos', id: this.status.ownId, node: this.self.node }, this.self.name);
    const incident = this.network.incidents.get(key);
    if (!incident.ack) incident.status = this.status.ownAcked ? 'Remote receipt confirmed by device' : 'Queued on device; awaiting remote receipt';
  }
  async refreshStatus() {
    this.status = parseStatus(await this.queue.request(Uint8Array.of(0x70), [0x70]));
    this.updateOwnIncident();
    if (!this.status.provisioned) { this.onLog('Network provisioning unavailable; disconnecting'); await this.close(); }
    this.onChange();
  }
  async rename(name) {
    this.requireReady(); await this.queue.request(nameCommand(name), [0]);
    this.self = parseSelf(await this.queue.request(appStart(), [5]));
    if (this.self.name !== name) throw new Error('Device did not save the requested name');
    this.onChange();
  }
  async sendText(text) {
    this.requireReady();
    await this.queue.request(channelMessage(text, this.self.name, Math.floor(Date.now() / 1000)), [0]);
    this.onLog('Device accepted message into transmit queue; remote receipt is still unconfirmed.');
  }
  async sendEvent(type, ack) {
    this.requireReady();
    const random = crypto.getRandomValues(new Uint8Array(4));
    const id = this.self.node + Array.from(random, (b) => b.toString(16).padStart(2, '0')).join('');
    const event = { type, id, node: this.self.node, ...(ack === undefined ? {} : { ack }) };
    await this.sendText(encodeEnvelope(event));
    this.network.sent(event, this.self.name); this.onChange(); return event;
  }
  async close() {
    if (this.closed) return;
    this.closed = true; this.ready = false; clearInterval(this.keepalive); this.queue.close();
    try { await this.transport.close(); } finally { this.onDisconnect(); this.onChange(); }
  }
}
